
PunktDe:
  CodeView:
    loadCSS: true
    loadJS: true
Neos:
  Neos:
    fusion:
      autoInclude:
        PunktDe.CodeView: true
  Fusion:
    defaultContext:
      'PunktDe.CodeView.Highlight': 'PunktDe\CodeView\Eel\Helper\HighlightHelper'
